Week 7: Enable/disable sound (on/off) for send-message button
badgerbadgers/ctd-sparrow-chat-app pull request #176
Opened 2022-09-10 14:25 UTC by asaiapalacios

closes #172 

used React Context API to create a global state for sound (default disabled sound state)
used Reducer and useReducer hook to update this global state (enable if user selects sound option - boolean true)
wrapped sound context provider to BottomInputComponent 
result: BottomInputComponent has access to the sound context value (sound on or off)
added and styled sound-on and sound-off button icons (sound-on button links to button sound effect when clicked)
![sound-on-off-button](https://user-images.githubusercontent.com/14948113/189487790-53d937e1-77bf-4103-9dc9-eaed8d6d1d5b.png)

2022-09-10 16:37 UTC, badgerbadgers commented
Works great! :)

2022-09-10 16:42 UTC, badgerbadgers requested changes
Just one small change Asaia by default there is no sound but the image shows picture with musical note. If you can switch the images to the image below(crossed out musical note) it should work and get approval for me! 
<img width="288" alt="Screen Shot 2022-09-10 at 9 38 37 AM" src="https://user-images.githubusercontent.com/39227111/189493155-a45b5e49-58f2-47ec-9d97-74fb63898ced.png">


Other than that awesome work! Glad applying context to the project has made other tasks easier. Also great job implementing a feature with useReducer!

2022-09-10 17:08 UTC, asaiapalacios commented
All set. Glad to get feedback on what makes sense for users -> show image with crossed-out musical note to indicate no sound (default state). 

Yes, implementing Context and useReducer was so useful for my knowledge gap! Although I understand this sound-on/sound-off case is not dealing with complex state, I found it quite educational to employ useReducer for learning sake.

2022-09-10 17:42 UTC, badgerbadgers approved these changes
LGTM! awesomeness!

2022-09-10 17:44 UTC, merged

2022-09-11 16:04 UTC, viniciuspietscher commented
Sorry just reading this now,

I think Asaia had it right the first time, the button should indicate the desired behavior to the user.

Since the app starts without sound it makes sense that the button it is not crossed by default, indicating to the user he can have sound if he clicks the button.

And if he clicks to enable sound it should be crossed to indicate to mute all sounds.

2022-09-11 16:23 UTC, asaiapalacios commented
That's what my brain was thinking, but I wasn't sure if this was accurate. Okay, will make the switch back.

2022-09-11 18:55 UTC, asaiapalacios commented
Pull request for the requested change here: https://github.com/badgerbadgers/ctd-sparrow-chat-app/pull/178